Cargo.toml, src/elf/dyn.rs, src/elf/header.rs, src/elf/mod.rs, src/elf/program_header.rs, src/elf/rela.rs, src/elf/sym.rs, src/lib.rs
Extends the `from_fd` functions to consider the byte order of all integers in the ELF file. Adds a dependency to the `byteorder` crate.
=> Foreign Endianess

src/elf/_32/dyn.rs, src/elf/_32/mod.rs, src/elf/_32/rela.rs, src/elf/_32/section_header.rs, src/elf/_64/rela.rs, src/elf/mod.rs, src/elf/strtab.rs, src/lib.rs, src/mach/fat.rs, src/mach/header.rs, src/mach/mod.rs, src/mach/utils.rs
This tries to make the style more aligned to idiomatic Rust.
----
Very nice crate, indeed (Redox's ELF parser was getting unmaintainable anyway)!
If you don't mind, I have a some criticism, mostly idiomatic ones.
1. So, you seem to be writing Rust the same way you would write C. You would make everything much cleaner if you made more use of Rust's type system and other abstractions.
1. Use the enum! You make use of the constant integer approach. Unfortunately, this makes code somewhat hairy. You could eliminate classes of bugs as well as writing more clean and idiomatic Rust code, if you made more use of enums. One particularly handy features is the ability to define the discriminant and then cast it to an integer (`my_enum_value as u8`). Instead of the 100 lines of constant declaration, …
=> Mostly style improvements & criticism

Cargo.toml, src/elf/dyn.rs, src/elf/header.rs, src/elf/program_header.rs, src/elf/reloc.rs, src/elf/section_header.rs, src/elf/sym.rs, src/lib.rs
Wrapped in a separate tiny crate this time, because it's just that bit of functionality that totally should be in core. It is possible to go one step further and implement #[derive(Plain)], with static checking of the prescribed requirements, but I'm not yet guru enough to do that.
=> Replace unsafe bits using crate `plain`.

src/pe/debug.rs, src/pe/mod.rs
Contemporary PE files use external debugging information stored in [PDB files](https://github.com/Microsoft/microsoft-pdb). Since these files are separate, it's important to collate them properly, since there are few things more aggravating than debugging with data that's only _slightly_ incorrect.
PEs and PDBs both have a long history in general, and they also have a long history of different solutions to this problem. This PR adds enough support to do things [the modern way](https://llvm.org/docs/PDB/PdbStream.html): the debug table data directory points to a `ImageDebugDirectory`, which points to a `CodeviewPDB70DebugInfo`, which holds a GUID.
There's other fields in each data structure and other data structures possible via different magic numbers, but as far as I can tell, that one …
=> pe: Add enough debugging support to locate PDB GUIDs

src/mach/mod.rs
`mach::MultiArch::get()`'s return value was missing a lifetime bound.
=> Fix mach::MultiArch::get() return value lifetime

.travis.yml, examples/dyldinfo.rs, src/mach/mod.rs, src/pe/debug.rs, tests/compare_dyldinfos.rs
This PR includes some fixes for Rust 1.16. (These are mostly things I broke, except for the `Fn` in `src/mach/mod.rs`.) It also expands the Travis build matrix to include 1.16 to avoid future regressions.
=> Rust 1.16 fixes

src/mach/load_command.rs, src/mach/mod.rs, src/mach/segment.rs
This is a stab at #29. Highlights:
* `ThreadCommand` now holds a `pub thread_state: &'a [u8]`. This required plumbing `<'a>` down through `CommandVariant` and `LoadCommand`, but should permit `ThreadCommand` to be round-tripped in a way that's faithful to the original bits.
* `ThreadCommand::instruction_pointer(cputype: CpuType)` can fish out a `u64` from `thread_state`. Unfortunately, the `flavor` in the load command doesn't actually specify anything useful here -- we really do need the `cputype` from the Mach header to fish out the right register. I've verified that it works for i386 and x86-64 binaries, and I wrote handlers for ARM though I don't have any binaries with which to test.
* The earlier issue discussed making the `LC_MAIN`/`LC_UNIXTHREAD` distinction a flag, but while …
=> Re-work Mach entrypoints

.travis.yml, src/archive/mod.rs, src/strtab.rs, tests/archive.rs
I think this closes #16. This commit makes `archive/mod.rs` no longer contain any `String`s.
=> Remove the last Strings from Archive

src/archive/mod.rs
I guess `__.SYMDEF SORTED` was invented to make symbol lookups faster? At any rate, some Mac archives have these instead of `__.SYMDEF`, and parsing them as if they were `__.SYMDEF` works fine, so this change makes that happen.
=> Treat "__.SYMDEF SORTED" as an alias of "__.SYMDEF"

src/mach/header.rs
Currently on 32bit headers the cpusubtype is read from the wrong byte which causes the value to effectively always be 0.
I am not entirely sure why this uses paddings in the header. If you look at the apple sources both cputype and cpusubtype are defined as i32 and the caps are fetched from the latter. I'm not sure if splitting it up into type + 2 byte padding + caps is correct here but I leave it unchanged because I do not understand the problem fully.
=> Correct broken cpusubtype field in Header32

src/mach/segment.rs
This avoids panicking when iterating over sections if an improperly
truncated macho files is encountered.  This is happening for files
that are provided by customers we have no control over.  These files
currently read fine with macOS tools presumably because those sections
are not ever used (we only care about DWARF data).
I unfortunately cannot share those affected files for a testsuite as it's
coming from customer data.
=> Work around truncated macho files

src/mach/constants.rs, src/mach/fat.rs, src/mach/header.rs
This adds the mapping of cpu names (flags) to the types that is also used
by apple and others. It's the mapping we (@getsentry) use and this is also
used by rust-macho. One modification I made to the table is register x86
as alias for i386 which we encounter in some cases.
It also changes the debug output to no longer show the cpu names but instead
the code which is easier to work with and consistent with other tools.
=> Add support for cpu names

src/mach/symbols.rs
I needed the `N_STAB` constant, because if any of those bits are set then the `N_TYPE` bits have different meanings.
I also added the other new constants for completeness. Names and comments came from `nlist.h`.
However, `N_TYPE` already exists as `NLIST_TYPE_MASK`. So not sure if you want to keep both, or delete one of these, or rename the new constants I'm adding to include `MASK` in their name.
I also updated the `NList` helper methods to use these constants for consistency. This includes a semantic change to `is_global` since it is valid to have both `N_EXT` and `N_PEXT` set.
=> mach: add more n_type mask constants

src/lib.rs
I think you forgot this one. :)
=> Remove the use of `goblin::parse` in `lib.rs` example

Cargo.toml
As embarassing as it is to admit, there was a potential integer overflow in `plain`. I don't know for certain that goblin is affected, but you should probably rebuild the package just to be sure.
=> Bump version of the `plain` dependency.

Cargo.toml, Makefile, src/archive/mod.rs, src/elf/dyn.rs, src/elf/header.rs, src/elf/mod.rs, src/elf/note.rs, src/elf/program_header.rs, src/elf/reloc.rs, src/elf/section_header.rs, src/elf/sym.rs, src/error.rs, src/lib.rs, src/mach/exports.rs, src/mach/fat.rs, src/mach/header.rs, src/mach/imports.rs, src/mach/load_command.rs, src/mach/mod.rs, src/mach/segment.rs, src/pe/export.rs, src/pe/import.rs, src/pe/mod.rs, src/pe/utils.rs, src/strtab.rs
This allows building the `endian_fd` feature without `std`, although it does still require the `alloc` crate and a nightly rustc.
Fixes #75
=> Add alloc feature

src/pe/import.rs, src/pe/mod.rs
I noticed that only the first imported symbol from each library is being parsed in 64-bit PEs. This is one way to fix it.
=> Fix parsing of PE32+ import tables

src/elf/compression_header.rs, src/elf/mod.rs
We need to read these headers to process `SHF_COMPRESSED` sections, which system debuginfo packages for various Linux distributions sometimes use.
=> Implement support for ELF compression headers

src/elf/reloc.rs
This avoids these values getting truncated when reading a 64-bit ELF files from a 32-bit platform.
[breaking-change]
=> Use u64/i64 instead of usize/isize for r_offset and r_addend

src/elf/sym.rs
Together with https://github.com/m4b/scroll_derive/pull/6, this significantly improves the performance of `SymIterator`.
When iterating through an ELF file with 2.5M symbols:
Before: 219ms
After: 120ms
=> Inline symbol-related methods

src/elf/note.rs
After discussion in [https://github.com/m4b/goblin/issues/90](url) I made some fix.
=> treat note  alignments as in readelf

src/pe/export.rs, src/pe/header.rs, src/pe/mod.rs
IMHO, goblin parser might be "too strict" in parsing export directory table and export entries of "abnormal" PEs. 
First, goblin will [refuse](https://github.com/m4b/goblin/blob/master/src/pe/export.rs#L77) parsing a PE if it cannot get the RVA of the name pointer table. In fact, an executable PE can have this RVA invalid, for example [this sample](https://github.com/corkami/pocs/blob/master/PE/bin/exportsdata.exe) from Corkami is a totally valid PE (it can even execute), but goblin will reject this PE.
Second, goblin parses export entries using [number of names](https://github.com/m4b/goblin/blob/master/src/pe/export.rs#L235) it found in the `export name pointer table` (and not from `number of names`), it will [stop parsing and reject](https://github.com/m4b/goblin/blob/master/src/pe/expo …
=> Parsing PE export

.travis.yml, README.md, src/archive/mod.rs, src/lib.rs
Also update required rustc to 1.19.
Fixes #94, cc @gz
=> Update path to BTreeMap in alloc crate

src/pe/debug.rs, src/pe/export.rs, src/pe/import.rs, src/pe/mod.rs, src/pe/utils.rs
Hello all,
The  `pointer_to_raw_data` of each section should be [rounded down](https://reverseengineering.stackexchange.com/questions/4324/reliable-algorithm-to-extract-overlay-of-a-pe) to a multiple of 512. Moreover, the [valid address range](https://github.com/m4b/goblin/blob/master/src/pe/utils.rs#L15) of each section should be [calculated](https://reverseengineering.stackexchange.com/questions/4324/reliable-algorithm-to-extract-overlay-of-a-pe) using also `size_of_raw_data` and `file_alignment`, e.g. [quine.exe](https://github.com/corkami/pocs/blob/master/PE/bin/quine.exe) has `virtual_size` (of its unique section) is zero, but it is a valid PE.
To make the review becomes easier, I split the [previous PR](https://github.com/m4b/goblin/pull/98) (which is closed), into parts.
Many …
=> Calculate number of read bytes for sections using file alignment

src/pe/mod.rs, src/pe/section_table.rs
Fixes #99 
An early PR to get some reviews, as there are probably better ways to do this. I need to implement the base64 kind of section table names, and fix the error handling in some places.
=> Get proper name for over-8-character sections

src/mach/constants.rs
This is for the new iphones. Travis fails for unrelated reasons (scroll bumped to 1.20 in a minor version upgrade).
=> Added arm64e architecture

src/elf/mod.rs, src/elf/reloc.rs
I think the provided iterator implementation and boilerplate does what is needed to lazily parse relocations.
=> Implemented a solution for #67

src/elf/dyn.rs, src/elf/mod.rs, src/pe/section_table.rs, src/pe/utils.rs, tests/archive.rs
Partial fix for #106 
Note that this changes `elf::dyn::DynamicInfo` so that it is no longer the same as `elf::dyn::dyn32::DynamicInfo`.
=> Handle multiple LOAD program headers with different biases

src/elf/mod.rs
=> Use hash table to determine number of dynamic symbols

src/elf/mod.rs
=> elf: use relocations to find number of dynamic symbols if hash is empty

src/elf/mod.rs
=> elf: parse shdr_relocs even if binary type is not ET_REL

src/elf/sym.rs
Required for https://github.com/m4b/faerie/pull/68
=> elf: add symbol table visibility definitions

src/elf/dyn.rs, src/elf/mod.rs, src/elf/sym.rs
This fixes all the errors that I could reproduce from #120.
TODO:
- validate all other `Vec::with_capacity`
- validate all other arithmetic for overflows
=> elf: handle some invalid sizes

src/pe/import.rs
hi! In an interesting choice in the PE format, it's possible for an import thunk to have a null import lookup table, but still list imports. In that case, the loader can/will check the referenced IAT for RVAs of hints just as the lookup table would reference.
goblin doesn't know that, so PEs that have a null lookup table RVA in an import thunk just appear to have no imports. I don't have a particularly good test case to share, but RollerCoaster Tycoon Deluxe does this with its import thunks
from what I can tell, this change is correct, but I don't see any tests around PEs, so I just know RCT.EXE has imports now where it didn't before :D
edit: forgot the relevant bits of MSDN that I was going to include: the [Import Address Table](https://docs.microsoft.com/en-us/windows/desktop/Debug/pe-fo …
=> PE: check IAT for import entries if lookup table is null

CHANGELOG.md, src/archive/mod.rs, src/elf/compression_header.rs, src/elf/dyn.rs, src/elf/dynamic.rs, src/elf/mod.rs, src/elf/program_header.rs, src/elf/section_header.rs, src/elf/sym.rs, src/error.rs, src/lib.rs, src/mach/fat.rs
=> Fix compliant after upgrading to Rust 2018 edition

README.md
Also clean up lines longer than 100 chars.
Rendered version: https://github.com/lzutao/goblin/blob/readme/README.md
=> Clean up README for pointing out lowest rustc version

src/pe/exception.rs, src/pe/mod.rs
This implements parsing for the exception tables data directory and x64 unwind codes. Respective documentation from Microsoft is located here: https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2017.
The exception directory is only present on x64 builds, so the entire implementation can assume x64 exception handling.
Tests are still missing as I haven't taken the time to extract relevant bits from an actual executable for realistic testing yet.
=> Implement PE exception tables

src/pe/import.rs
IMPORT_RVA_MASK_32 and IMPORT_RVA_MASK_64 was using the wrong mask, correct it so the least significant 31-bits are included and everything else is masked off.
=> Correct IMPORT_RVA_MASK_32 and IMPORT_RVA_MASK_64

src/pe/header.rs, src/pe/mod.rs, src/pe/symbol.rs
Reuses the existing parsing for the COFF header and sections, and adds COFF symbol parsing.
Work for future PRs:
- auxiliary symbol records
- COFF relocations
- write support
=> Basic COFF support

src/pe/mod.rs, src/pe/relocation.rs, src/pe/section_table.rs, src/pe/symbol.rs
Only the section and file auxiliary symbol records have had any testing, since I don't know how to generate the others.
=> pe: add COFF relocations and auxiliary symbol records

src/pe/header.rs, src/pe/mod.rs, src/pe/relocation.rs, src/pe/section_table.rs, src/pe/symbol.rs
See https://github.com/philipc/object-write/blob/master/src/coff.rs for an example of its usage.
=> pe: add write support for COFF object files

.travis.yml
Closes #156 .
Note you need to set up [GitHub person access token](https://github.com/settings/tokens)
then save it in [Travis settings](https://travis-ci.org/m4b/goblin/settings) under the name `GITHUB_OAUTH_TOKEN`.
=> Enable deploying nightly doc

src/mach/constants.rs, src/mach/load_command.rs, src/mach/relocation.rs
This is used by the new Apple Watch. I have tried to get this as close as possible to what LLVM does, but I'm not 100% sure about the relocations mapping.
=> Add constants for ARM64_32 (ILP32 ABI on 64-bit ARM)

src/pe/header.rs, src/pe/section_table.rs, src/pe/symbol.rs
I don't know if there's a better way to do the number printing without `io::Write`.
=> Fix alloc build

src/mach/segment.rs
When parsing [BoringSSL](http://boringssl.googlesource.com/boringssl/)'s object files built on macOS I had goblin failing on some with `bad offset x` where x is outside of file boundary (pointing at the byte right after the end of the object). It _might_ be a toolchain bug but since such binaries exist it would be useful if goblin could handle them. objdump does not fail to parse those files nor Go's Mach-O parser does. The easiest way to reproduce the problem is to build BoringSSL and run bingrep on cpu-aarch64-fuchsia.c.o ([a copy in my Dropbox to save time](https://www.dropbox.com/s/rsvpwtqyikokn8b/cpu-aarch64-fuchsia.c.o?dl=1)) or fuchsia.c.o.
I've intentionally only checked `fileoff` being outside of file boundary and not `fileoff + filesize` to not hide problems when an object file …
=> Handle fileoff out of file boundary in load segment commandj when parsing Mach-O

src/archive/mod.rs
Implement parsing of Windows-specific Second Linker Member in SysV archives. Also fix the parser going out of boundaries if the archive is aligned.
I have verified that the parser succeeds on the samples from both #173 and #133. I was thinking about automated tests but it's quite ugly bringing binary data into the repository for testing. I think using cc crate to build binaries from source might be a better approach. With a Windows Travis pipeline the CI can verify parsing of PE binaries as well.
=> Fix parsing of Windows library archives

src/archive/mod.rs
Fail fast rather than attempting to parse and overwriting already initialized symbol index. Came up in
https://github.com/m4b/goblin/pull/174#discussion_r302866012.
=> Be more strict about multiple indexes found in an archive

src/pe/export.rs
=> pe.export: fix reexport dll and ordinal

src/pe/mod.rs
pe: Should parse .pdata on for machine X86_64 only. (what llvm does)
See detail from https://github.com/m4b/goblin/issues/179
=> pe: only parse ExceptionData for machine X86_64

src/elf/dynamic.rs, src/elf/gnu_hash.rs, src/elf/section_header.rs, src/mach/segment.rs, src/pe/debug.rs, src/pe/exception.rs, src/pe/import.rs, src/pe/section_table.rs
Taking a closer look at the test failures on beta it seems like `repr(C)` is broken now on Beta. The compiler introduces additional padding around `u32` fields that are already aligned. There were a bunch of other warnings that are now fixed in this PR, but the core problem still exists.
=> Fix errors, warnings and lints on Beta

src/elf/mod.rs
It seems some tools leave a PT_INTERP Phdr in a
bad way when manipulating the ELF file (for example,
https://bugzilla.redhat.com/show_bug.cgi?id=1770513 where splitting debug
info into a separate file leaves a bogus PT_INTERP header). When using
`gimli` with `object` to parse DWARF info, the PT_INTERP is irrelevent
so failing to load the file because of it causes loss of functionality.
This PR just ignores the PT_INTERP if it can't be
parsed/loaded/used. Another option would be to keep it as an
`Option<Result<_, _>>` so that any errors can be preserved but deferred
until someone tries to use the interp information.
=> Elf: Ignore bad PT_INTERP rather than completely failing

src/mach/segment.rs
I'll also guess that the big comment I'm indenting here was a result of these sections (it's still good to have correct handling for truncated files of course).
=> mach: don't return data for zerofill sections

src/elf/dynamic.rs
Some ELF files may contain `PT_DYNAMIC` program headers that have a zero `p_filesz` pointing to invalid memory if the corresponding section has been stripped. This currently causes an error when parsing the dynamic headers.
=> Support ELF with empty PT_DYNAMIC reference

src/elf/section_header.rs
Regression in 779d0ce8 (which wasn't reviewed...).
Fixes #199, cc @xcoldhandsx
=> elf: handle zero offset in SectionHeader::parse

Cargo.toml, examples/ar.rs, examples/dyldinfo.rs, examples/lipo.rs, examples/rdr.rs, src/lib.rs, tests/archive.rs
We sort the `package` section based on https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/cargo.md
@m4b Do we need to include `examples`, `tests` and `fuzz` directories
in goblin crate?
=> Get build artifact path reliable with std::env::current_exe

src/mach/relocation.rs
I haven't looked for any binaries to test this on, but it matches the definitions in LLVM and system include files.
=> mach: fix generic reloc constants

src/elf/dynamic.rs
This is useful and convenient for assertions.
=> elf.dynamic: derive PartialEq for DynamicInfo

src/elf/dynamic.rs
Defined here in binutils:
http://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=include/elf/common.h;h=53b72445cafd079c16e7742ab4a72e6d2a2b68d3;hb=HEAD#l1092
`readelf` will report this flag:
```
$ ld -pie -o main main.o
[ .. ]
$ readelf -a main | grep PIE
0x000000006ffffffb (FLAGS_1)            Flags: PIE
```
and so there's no reason why tricksy `goblin`s couldn't! :grinning:
=> elf.dynamic: export ELF PIE flag

src/elf/dynamic.rs
The [elf::dynamic::DynamicInfo](https://docs.rs/goblin/0.2.0/goblin/elf/dynamic/struct.DynamicInfo.html) struct has a couple of fields missing from the debug output.
This pull request adds the missing fields. Also, for the bit vector fields like `flags` and `flags_1`, I added the symbolic names of each of the flags that are set by adding additional lookup tables for string representations of the field names like `tag_to_str`
For example (with many fields omitted for brevity):
```
DynamicInfo {
[...]
flags: 0x000000 [],
flags_1: 0x8000000 ["DF_1_PIE"],
[...]
}
```
=> Add missing fields to DynamicInfo's debug output

src/elf/mod.rs, src/elf/program_header.rs, src/elf/section_header.rs, tests/elf.rs
Malformed or malicious ELF files may trigger an OOM condition when pre-allocating vectors for program or section headers.
Prevent this by doing a quick and safe sanity check before doing the allocation.
This issue was found by fuzzing `goblin::elf::Elf::parse` using a valid ELF as a seed.
=> Protect against OOM when calling Vec::with_capacity

src/pe/exception.rs
The exception handler address incorrectly shadowed the `offset` for reading exception handler data. This could lead to out-of-bounds access which and results in a panic.
Instead, the address should be treated as an opaque pointer (relative, probably RVA), while the data follows the pointer. See https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64
=> Fix panic in parsing UnwindInfo

src/pe/header.rs
The `unwrap` was causing some problems in my code and it seems unnecessary since the function returns the same Result type as what is being unwrapped anyway.
=> Replaced CoffHeader::strings unwrap with try.

src/pe/header.rs
Added all of the COFF machine constants found here:
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format
(sorry about the multiple pull requests)
=> Added more COFF machine constants.

src/elf/section_header.rs
As specified in https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf section 4.2.2.
=> Add the x86-64 unwind processor specific section header type.

src/archive/mod.rs, tests/archive.rs
Also add a `len()` method to give the number of files (which might be different to `members().len()`, and add warnings about duplicate file names.
Fixes #226
=> Add ability to get archive members by index

src/elf/gnu_hash.rs
Previously, there are no validation for unused attributes like
`#[cold]`. Now starting with rust-lang/rust#73461, "cold" can only
be used in function or method definitions.
=> Fix unused `#[cold]`

src/elf/program_header.rs, src/error.rs, src/lib.rs, src/mach/constants.rs
Sorry if this PR is just noise, but I saw some other commits cleaning clippy warnings up.
I'm happy to squash this into 1 commit too, if that's the preference.
edit: the clippy output is saved in each commit
=> Resolve clippy lints

src/mach/constants.rs
Related issue: #231 
Some users may use `cputype` and `cpusubtype` directly to get architecture name, which may leads to wrong answer.
For example:
```rust
let buf = read("path/to/macho").unwrap();
if let Ok(Mach::Binary(a)) = Mach::parse(&buf) {
println!("arch name: {}", get_arch_name_from_types(a.header.cputype, a.header.cpusubtype).unwrap());
}
```
When apply this to [arm64e](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication) arch Mach-O file (which may be the main arch of iOS app and Apple Silicon Mac's app), the program crashes because the `get_arch_name_from_types` returns `None`.
From Apple's open source [lipo](https://opensource.apple.com/source/cctools/cctools-949.0.1/misc/lipo.c.auto.html) code, we can find the code to …
=> mach.constant: add more document for get_arch_name_from_types to avoid misuse

src/lib.rs
This PR is to avoid std for the `parse` method of `Object`.
The reason that `parse` need std is `peek` needs it, and `peek`'s task is:
1. take the first 16 bytes of the total bytes;
2. pass the taken array of 16 bytes to `peek_bytes` method.
And there is a no-std way to take the first 16 bytes of the total bytes:
```rust
fn take_hint_bytes(bytes: &[u8]) -> Option<&[u8; 16]> {
use core::convert::TryInto;
bytes.get(0..16)
.and_then(|hint_bytes_slice| {
hint_bytes_slice.try_into().ok()
})
}
```
The core magic is [`get`](https://doc.rust-lang.org/std/primitive.slice.html#method.get) (which takes the first 16 elements of the given slice and returns a slice) and the `TryInto` trait (which converts the slice to array type, see more in [How to get a slice as an array in …
=> lib.parse: use TryInto trait to replace peek to make parse not need std

.github/workflows/main.yml, README.md, src/mach/load_command.rs
First of all, thanks for this library! It's a pleasure to use.
I'm the maintainer of [ruby-macho](https://github.com/Homebrew/ruby-macho), and I noticed that these load commands were missing from your Mach-O implementation. I've taken the liberty of adding them; please let me know if there's anything else I can do.
---
Commit message:
Adds support for `LC_VERSION_MIN_{TV,WATCH}OS`, as well as
`LC_VERSION_EXPORTS_TRIE` and `LC_VERSION_CHAINED_FIXUPS`.
Each of the above maps to a pre-existing load command structure,
so no additional structure definitions were necessary.
Also adds constant support for `LC_NOTE` and `LC_BUILD_VERSION`.
These require new load command structures (and substructures, in the
case of `LC_BUILD_VERSION`), so I left them out of this PR in
the interest of brevity. I …
=> mach/load_command: Add some missing load commands

src/elf/section_header.rs
Fuzzier found an overflow if bad section address or size.  
- Update `check_size` to also check addr + size
- Use saturating addition to prevent overflow or a wrap-around region bound if `check_size` is not called on a created section.
=> elf: prevent overflow

examples/dyldinfo.rs, tests/compare_dyldinfos.rs
As of Big Sur, even on Intel macOS machines, developer tools contain
both x86_64 and arm64 slices. This updates the dyldinfo example / tests
to only output the binds for x86_64.
=> Fix tests for multi-arch macOS binaries

src/elf/section_header.rs
The section header size check introduced in #243 compares the virtual memory
address range `sh_addr` with the physical file size. This leads to a
false-positive invariant violation and fails to parse valid ELF files.
See also https://github.com/m4b/bingrep/issues/28
cc @jackmay
=> Fix size check for section headers

src/mach/mod.rs
=> Fix MultiArch Debug impl panic

src/elf/section_header.rs
ELF sections with type SHT_NOBITS only exist in memory, and
don't contain any data in the ELF file itself. The range
returned by `file_range()` should be empty for such sections.
The previously returned range was wrong, and overlapped
the file range of the next section.
Fixes #252.
=> Return an empty file range for SHT_NOBITS sections

src/pe/debug.rs, src/pe/exception.rs, src/pe/export.rs, src/pe/import.rs, src/pe/mod.rs, src/pe/options.rs, src/pe/utils.rs
It would be extremely helpful to use the capabilities of goblin when working with memory/process dumps as well as files on disk. Since memory dumps are already mapped we can just skip over the rva resolve function and all of the other functionality will work still.
I'm not sure however if it would be best to implement this as a compile-time feature (as this PR does it) or as a runtime feature (maybe splitting the parse function into parse_image / parse_mapped or something similiar.
=> Added a feature to disable pe rva resolve for already mapped modules

src/elf/mod.rs, tests/bins/elf/gnu_hash/README.md, tests/elf.rs
We are developing a libOS kernel (https://github.com/occlum/occlum) and would like to load ELF as lazy as possible. However, now goblin does all the read and parse in memory so we must read the whole ELF file to kernel memory (we can't mmap the file to memory due to some constraint).
Thus, I came up with this method to load lazily:
read ELF header only -> parse header -> get program header table -> only read in PT_LOAD and PT_INTERP segments
And by adding these two functions, I can achieve this. The implementation can be found [here](https://github.com/occlum/occlum/pull/315). I would like to see this get merged to master so that people with similar requirements can do this. But I am not sure if it is a common need. If it is, I can spend some time to reduce the repeated code.
Comments are …
=> elf.parse: added lazy_parse function

examples/lazy_parse.rs
This example shows how to use a lazy parse manner to reduce the read IOs and to save time by parsing only parts we care about.
=> example: add lazy parse example

src/pe/data_directories.rs
This pull request replaces get_unchecked calls with direct indexing ( [] ). This removes a bunch of unsafe blocks
As far as I can tell, this should not affect optimized code: Since rust statically knows the size of the array, it should be able to elide the bounds checks
This [godbolt link](https://rust.godbolt.org/z/Pd19W6) shows how both the version with and without the unsafe are compiled to the same function with opt-level=3. [This](https://rust.godbolt.org/z/Wrb3eT) is the same example without the derives adding noise to the output
What I found interesting is, according to [this godbolt link](https://rust.godbolt.org/z/4dzs53) when compiling without optimizations, rust also elides the bounds checks for the indexing version, and the get_unchecked version has to call the get_unchecked …
=> Remove unneeded unsafe in data_directories.rs

fuzz/Cargo.toml, fuzz/fuzz_targets/parse_elf.rs, src/elf/mod.rs
This adds a new fuzzing harness that covers most of the ELF module and fixes a few overflow assertions.
`saturating_add`s should be fine since all of the edge cases concern sizes that are bounds-checked later.
(Xref #110)
=> Fix arithmetic debug assertions in elf

tests/elf.rs
[This test](https://github.com/m4b/goblin/blob/48f6ad968309cb0acfc0364d269763572cc35c6a/tests/elf.rs#L20-L23) performs the equivalent of subslicing a slice through unsafe code and avoids the bounds checking:
```rs
let hashtab: &[u8] = unsafe {
let addr = base.as_ptr().add(hash_section.sh_offset as usize);
let size = hash_section.sh_size as usize;
slice::from_raw_parts(addr, size)
};
```
Since it's a test, I expect the bounds checking to not matter (I also expect that any potential overhead is dwarfed by everything else this function is doing like the vec allocation or the Elf parsing)
=> Replace unchecked unsafe slicing with regular slicing in elf test

src/pe/import.rs
related: https://github.com/m4b/goblin/issues/267
The problem here was solved by using parse_with_otps.
I had some time, so I debugged and confirmed that the problematic code I presented didn't cause any problems.
No tests were added because I didn't have time to write the tests.
If you have time, please help me :<
=> Fixed #267

src/elf/reloc.rs
See issue #272 for details.
Signed-off-by: Dan Cross <cross@gajendra.net>
=> build: fix error when alloc, but not endian_fd

src/archive/mod.rs, src/elf/dynamic.rs, src/elf/mod.rs, src/pe/symbol.rs, src/strtab.rs, tests/elf.rs
Together with @jackcmay I am working on a [BPF VM](https://github.com/solana-labs/rbpf), which utilizes goblin for loading user provided ELF files.
So, last week we encountered a problem with the way `Strtab::get()` works, tried to fix it outside, which did not work and now have found a fix which would require upstream changes. Furthermore, I think these changes can also help other projects depending on goblin which are exposed to potentially hand-crafted adversary / worst case inputs too.
A `get` request performs a linear scan to find the separators / `NULL` termination and possibly invalid UTF-8 variable length encodings on every single request. So it is possible to construct e.g. an ELF file which is only a few MiB in size but has massive overlap in the `Strtab`. This way everything …
=> Parse Strtab only once on Creation

src/elf/program_header.rs
These masks indicate program header flag bits that are reserved for OS
and processor specific usage. See the ELF specification for details.
Signed-off-by: Nathaniel McCallum <nathaniel@congru.us>
=> Add PF_MASKOS and PF_MASKPROC

src/elf/mod.rs
MachO already has rpaths added in #248
=> Add rpaths and runpaths to ELF

src/pe/export.rs, src/pe/utils.rs
This PR is a replacement for #292, which applies the change discussed there: 
- make offset an `Option<_>` in `Export`, and support when an `Export` has no offset.
Moreover, the correct commit of #292 (add missing subtraction) is retained.
The same procedure as in #292 was followed.
This change does fix the issue #291  and the previously missing symbols are now returned for the tested binaries. 
Thanks again for your time and consideration!
=> Support exports without offset

src/elf/mod.rs
Only parse the last `SHT_SYMTAB`, because all earlier ones are not used anyway.
This improves the runtime complexity from O(n^2) to O(n),
and makes the parsing more robust against crazy inputs.
=> Only parse the last `SHT_SYMTAB` in `Elf::parse()`

src/archive/mod.rs, src/elf/dynamic.rs, src/elf/program_header.rs, src/elf/section_header.rs, src/elf/sym.rs, src/error.rs, src/mach/exports.rs, src/mach/mod.rs, src/pe/export.rs, src/pe/header.rs, tests/macho.rs
The crate does a lot of pre-allocation based on untrusted input, which
can lead to unbounded allocation.
This came up in https://github.com/getsentry/symbolic/issues/479, and I see the crate already had some bounds checks for certain parts, though not for Mach-O parsing.
I went a bit overboard and added explicit bounds checks for every place where a `with_capacity` is called.
=> Guard every with_capacity call with a bounds check

src/elf/program_header.rs
=> elf: program_headers: fix arithmetic overflows in file_range() and vm_range()

src/elf/program_header.rs
* Expose more of the `ProgramHeader` implementation regardless
of whether the `alloc` feature is enabled.  For example,
`ProgramHeader::from_raw_parts` is a wrapper around
`core::slice::from_raw_parts` that has `alloc` dependency.
* Run `cargo fmt`.
Based on an internal patch by Keith Wesolowski (@wesolows).
Signed-off-by: Dan Cross <cross@oxidecomputer.com>
=> elf: Non-alloc `ProgramHeader` exposes impl.

src/pe/debug.rs
The well intentioned check on debug directory size unfortunately results
in an error when debug information is embedded in the image.
Tools like Digital Mars embed CV debug info in the image instead of
creating a PDB, and some older tools embed COFF debug info in the image.
=> Remove check on debug directory size

src/elf/note.rs
This implements Plain for both plain note headers.
What do you think?
=> Implement Plain for Nhdr{32,64}

src/elf/mod.rs, tests/elf.rs
This attempts to fix #304.  
With this patch, I no longer reproduce the issue using the same large object file that triggered it before.  
I've also updated the test code to handle XINDEX for the strtab, however I don't know a good way to generate a test case for an ELF file with >=2^16 sections without embedding a very large blob, so I've left it for future work.  
(If I've missed a simple way to do this, happy to do it now)
=> elf: Handle SHN_XINDEX for strtab section index (#304)

src/pe/mod.rs, src/pe/symbol.rs
I took a crack at #318 myself after attempting to do some investigation. It seems to me that the best place to adjust the offset was here in the pe specific symbol code since `strtab` looks to be at a higher level of abstraction. Apologies if I've missed something important here.
=> Adjust coff symbol offset to account for the strtable length field

src/archive/mod.rs
Hi!
We were doing some fuzzing with libFuzzer and our tool Sydr and found an unbound access to `member_offsets`:
`thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 3', /goblin/src/archive/mod.rs:342:23`
So, I propose this fix for that.
=> Fix unbound access to member_offsets in archive/mod.rs:342

src/pe/debug.rs
Hi!
We were doing some fuzzing with Sydr+libFuzzer and found this unbound access to bytes slice at  pe/debug.rs:172. Here is the panic message: `thread '<unnamed>' panicked at 'range end index 16256248 out of range for slice of length 4257', library/core/src/slice/index.rs:73`
I propose this fix.
=> Fix unbound access to bytes slice at  pe/debug.rs:172

src/elf/dynamic.rs
There is little point in using non-loadable segments for the VM address
translation. Ignore non-loadable segments.
=> elf.dynamic: only consider loadable segments for VM translation

src/archive/mod.rs
Our tool Sydr found an overflow. Here is the input: 
[crash-sydr_1d821e2a398a547fe1aa4a445c8f31d2c51761d6_int_overflow_1_unsigned.txt](https://github.com/m4b/goblin/files/9585735/crash-sydr_1d821e2a398a547fe1aa4a445c8f31d2c51761d6_int_overflow_1_unsigned.txt)
=> Fix substract with overflow for header.size

src/archive/mod.rs
Fix for #328. Direct indexing is removed in favor of `strip_prefix`.
=> archive: fix potential panic in bsd_filename_length

src/pe/header.rs
Add function returning string representation of the machine header, similar to `goblin::elf::header::machine_to_str()`.
Feel free to suggest improvements to the individual string representations.
=> pe: add machine_to_str

fuzz/Cargo.toml
This PR adds debug info to fuzz targets in order to see source lines in libFuzzer stack trace.
=> Enable debug info in fuzz targets

src/elf/reloc.rs
Some ELF files include a .rela section with size 0 instead of simply not including the section. This caused issues with the parser, since bytes.pread_with(offset, filesz) would try and read 0 bytes from a 0-length buffer, which returned an error. This workaround simply swaps out the value with the entire input when filesz is 0; this is the smallest change that appears to work, since count will then be set to 0. This could also be worked around by adding a check in elf.mod (or many other methods), but I thought that it was better to allow the parser to handle 0-sized sections.
=> elf.reloc: add workaround for 0-sized relas

src/mach/load_command.rs
=> mach: Implement `LC_BUILD_VERSION`

src/elf/section_header.rs
One more change necessary for the funky ELFs I have that I forgot to add previously is allowing check_size to immediately return Ok(()) on a 0-sized section, even if that section isn't marked as SHT_NOBITS.
=> elf.section_header: additional workaround for 0-length sections

src/pe/certificate_table.rs, src/pe/mod.rs
This is a rough PR to enable basic certificate enumeration in the PE structure.
I am planning to add support to transform the string binary data into a structured format using a PKCS#7 compatible library gated behind a feature flag maybe (?).
I'm not sure my implementation is optimal, let me know if I should simplify stuff.
For tests, I was planning to add PE binaries with a certificate and multiple certificates attached, checking the number of certificates found, would that work?
Later, I am also planning for write support, including attaching arbitrary signatures.
=> pe: support basic certificates enumeration

src/pe/certificate_table.rs
There appear to be an off-by-one error in the parsing of the certificate table. This error would occur when the cert table is at the end of the binary.
cc @RaitoBezarius
=> pe: fix certificate table parsing

fuzz-afl/Cargo.toml, fuzz-afl/fuzz_targets/afl_parse.rs, fuzz-afl/fuzz_targets/afl_parse_elf.rs, fuzz/fuzz_targets/parse_elf.rs
Hi! 
I think adding AFL++ fuzzing support  it's a good idea for finding new bugs. What do you think?
=> Add AFL++ fuzzing support

src/pe/authenticode.rs, src/pe/mod.rs, src/pe/optional_header.rs
Alternative to #358
This removes the `digest` dependency and allows to implement hashing like:
```rust
trait AuthenticodeDigest {
/// [`authenticode_digest`] returns the result of the provided hash algorithm.
fn authenticode_digest<D: Digest>(&self) -> Output<D>;
}
impl AuthenticodeDigest for PE<'_> {
fn authenticode_digest<D: Digest>(&self) -> Output<D> {
let mut digest = D::new();
for chunk in self.authenticode_ranges() {
digest.update(chunk);
}
digest.finalize()
}
}
fn main() {
let mut buf = Vec::new();
let mut f =
File::open("/nix/store/bhsxra1hc7yhja2kzw5rdds90i3w3a54-linux-5.10.147/bzImage").unwrap();
f.read_to_end(&mut buf).unwrap();
let pe = PE::parse(&buf).unwrap();
let hash = pe.authenticode_digest::<Sha256>();
println!("hash: {:x?}", hash);
}
```
=> pe: add authenticode support / v2

src/pe/certificate_table.rs
Hi!
During our fuzzing campaign we found an oob in `AttributeCertificateHeader::parse`. I proposed a fix.
=> Fix out of bounds access while parsing AttributeCertificate

src/elf/mod.rs
PIE executables (either static or dynamically linked) erroneously report `is_lib == true`, due to the fact that they have `e_type == ET_DYN` in their elf headers. 
To distinguish you have to check if the DT_FLAGS_1 was set in the dynamics section. 
The part that I'm not sure about is `lazy_parse`, which can't detect if something is a library or not.
=> Fix `is_lib` detection for PIE and static PIE Elf objects.

src/mach/load_command.rs
These 3 are all new with Xcode 15
=> Add new Mach-O constants

src/lib.rs
=> pe: add COFF object file support

src/pe/certificate_table.rs
Excerpt of https://learn.microsoft.com/en-us/windows/win32/debug/pe-format
> The options for the WIN_CERTIFICATE wRevision member
> include *(but are not limited to)* the following.
Emphasis mine.
=> pe: Attribute certificate revisions are non-exhaustive

Cargo.toml, src/pe/mod.rs, src/pe/options.rs
Per [this documentation](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#other-contents-of-the-file) (just above "Section Data"), the attribute certificate table is not loaded into memory along with the rest of the PE. This PR fixes #376 by adding a `ParseOptions` field that allows a user to skip parsing the attribute certificate table altogether, making parsing of loaded PEs possible.
=> Add `ParseOptions` field to toggle parsing Attribute Certificates for PEs loaded into memory

Cargo.toml, examples/dotnet_pe_analysis.rs, examples/rewrite_pe.rs, src/error.rs, src/pe/certificate_table.rs, src/pe/data_directories.rs, src/pe/header.rs, src/pe/mod.rs, src/pe/optional_header.rs, src/pe/section_table.rs, src/pe/symbol.rs, src/pe/utils.rs, src/strtab.rs
This implements reserialization for many in-memory structure with PE semantics.
It does not yet enable you to modify a PE and write it because you will need many modifications to the existing structure to avoid breaking the PE.
But you can already modify existing bytes this way.
I learned the hard way that this code may be insufficient to write the worst PE binaries out there (look the Corkami repositories on pocs and look for the PE there), I deem this to be out of scope for now as it is very hard to get all of this right.
Also, I don't think that identity rewrite should be a goal for anything else than "basic" and "simple" (read: nice) PEs, which can be accomplished in this PR with NixOS PE binaries for UEFI (and I tested a hundred of them).
Testing ways:
```console
cargo run --example …
```
=> Write support for PE binaries

src/pe/authenticode.rs, src/pe/mod.rs
When adding the signature, the last section of the file will be padded to 8-bytes align. We need to make sure the payload we feed to a signer is always padded to 8-bytes.
This fixes signature breakage.
cc @RaitoBezarius 
Thanks to @foxboron for the heads up!
=> pe: make sure authenticode is identical before/after signature

src/elf/sym.rs
Here is an example of modifying elf:
```rust
use goblin::elf::{section_header, sym::Sym, Elf};
use scroll::{ctx::SizeWith, Pwrite};
use anyhow::Result;
use std::fs;
fn main() -> Result<()> {
let path = "my.elf";
let mut buffer = fs::read(path)?;
let elf = Elf::parse(&buffer)?;
let ctx = elf.syms.ctx().clone();
for (index, mut sym) in elf.syms.iter().enumerate() {
let Some(name) = elf.strtab.get_at(sym.st_name) else {
continue;
};
if name == "my_symbol" {
let offset = elf.syms.offset() + index * Sym::size_with(elf.syms.ctx());
println!("name: {}, offset: {}", name, offset);
sym.st_shndx = section_header::SHN_ABS as usize;
sym.st_value = 0xeaeaeaea;
buffer.pwrite_with(sym, offset, ctx)?;
break;
}
}
Ok(())
}
```
https://github.com/m4b/goblin/issues/325#issuecomment-1288407913 shows that we …
=> elf: Add convenient functions for symbol write

src/pe/header.rs
I've noticed that there was little to no documentation of the DOS header, so I decided to add it. I've provided sources for all the claims that are made in the docs.
=> Documented the pe::header::DosHeader.

src/elf/section_header.rs, tests/elf.rs
=> elf: Allow parsing SectionHeader from raw bytes

src/elf/constants_relocation.rs, src/elf/dynamic.rs, src/elf/gnu_hash.rs, src/elf/reloc.rs, src/pe/authenticode.rs, src/pe/exception.rs, src/strtab.rs
All of these were reported by `cargo doc`. (This should probably have a CI job set up to fail on warnings).
For the authenticode change, I figured it wasn't really that important to link to the method that the doc is *on*, so I just deleted that. And for the strtab change, the anchor hash at the end of the url didn't seem to *link* anywhere relevant?
=> fix doc warnings

src/pe/characteristic.rs, src/pe/dll_characteristic.rs, src/pe/header.rs, src/pe/mod.rs, src/pe/optional_header.rs, src/pe/subsystem.rs
There's still some work needed for documentation of data directories field in the optional header but it's a separate module.
This PR also...
* introduces two new modules for constants that are used in the optional header (`dll_characteristic` and `subsystem`).
* further refines the documentation of the COFF header module.
=> Nearly fully documented the optional PE header.

src/mach/mod.rs, src/mach/segment.rs
Made it possible to parse MachO objects in less strict manner. However, default behavior is not changed. Therefore, there now is a new function `parse_2` which accepts additional argument for lossyness.
Open questions:
- Is the default behavior intended? If not, `parse_2` could be made private.
- Is `parse_2` sufficient name, or should this be called something like `parse_lossy`?
- I made all of the commands work without fail in lossy mode, however, maybe some should fail?
- Should `from_32_2` `from_64_2` on `Segment` be exposed to the public? I currently have it `pub(crate)`.
=> Support for lossy MachO parsing

src/pe/header.rs
This PR fixes `DosHeader::parse` by reading `reserved` and `reserved2` fields from the input instead of assuming that they are always zeros (PE64/32).
In the PECOFF, the DOS header fields except `e_lfanew` (the `pe_pointer` alias in the goblin) are entiely not read by the LDR (Windows loader). So assuming that the two fields in question does not really matter.
However, these fields are sometimes (and rarely) used by the PE packers for marking/watermaking purpose. In the real world example, Riot Games uses the `e_ss = 0x4952` and `e_sp = 0x544F` fields for `MZ ... RIOT` marker.
=> PE: read reserved DOS header fields

src/pe/mod.rs, src/pe/tls.rs
Parses TLS (thread local storage) data directory in PE64/32.
=> PE: parse thread local storage - TLS data

src/pe/tls.rs
- Fixed issue #424 where binaries compiled Rust, and binaries with `AddressOfIndex` only exists in virtual address caused Malformed error by simply not raising explicit error but set the `slot` field to `None`.
- Fixed similar issue where the `callback` terminator check must be right before it reads from the raw binary. Otherwise it overflows when subtracting by image base.
=> PE: Assume `AddressOfIndex` could not be in raw section, check callback is zero right after it reads from binary

src/pe/import.rs
- Addresses issue #371.
Sample: [sample.zip](https://github.com/user-attachments/files/17559872/sample.zip)
OFTs (Original First Thunk, aka lookup table) are kept as raw when mapped into virtual memory;
FTs (First Thunk, aka address table) are rewritten to the absolute address where the import function is located when mapped into virtual memory.
Static Import parsing would work fine on both cases, so use OFTs if FTs are zero, but keep FTs preffered.
=> PE: Use OFTs for resolving imports without FTs

src/pe/mod.rs, src/pe/tls.rs
- #433 
Changelists:
- Removed generics from `ImageTlsDirectory::parse*` and `TlsData::parse*`, instead added new argument `is_64` as proposed in the issue.
- Added slice bound check in `TlsData::raw_data` parser to compliant with panic-free design in goblin.
I personally prefer not making `ImageTlsDirectory32`―as it's more comfortable than the way duplicating the same kind of structs and merging to 64-bit as proposed in the issue.
This change should be marked as breaking-change and I expect this to be rolled up in 0.10.
=> PE: TLS parser rework

src/pe/header.rs
I think we shouldn't return `Error` before we even ensure that `Rich Header` present
=> pe.header: fix parse without rich header

src/pe/import.rs, src/pe/options.rs
In some PE files one part of imports may be corrupted, but another part of imports is ok, and I want to be able parse this files
=> pe.imports: ignore malformed imports in ParseMode::Permissive

src/pe/tls.rs
The check for the access of the bytes slice can be bypassed, by either a large 'offset' or using an integer overflow.  I attached the fuzzer test case to this post as well. 
[crash-37862deb65bdd4829ef254d5aabea5612f6453cc.zip](https://github.com/user-attachments/files/19397396/crash-37862deb65bdd4829ef254d5aabea5612f6453cc.zip)
=> pe.tls.tlsdata.parse_with_opts - integer overflow + out of bound

src/pe/load_config.rs
Hi guys, I think we have a typo here. I attached a binary as an example where it fails
[example.zip](https://github.com/user-attachments/files/20728727/example.zip)
=> LoadConfig cannot read cb size fix

.github/workflows/main.yml, src/pe/data_directories.rs, src/pe/optional_header.rs
While I was working on a personal project using both goblin and scroll, I found some bugs in the way offset are computed for both `DataDirectories` and `OptionalHeader`.
Here some minor fixes without breaking changes. 
While going through the code I notice that most parsing methods are present twices:
* one implementation with the scroll traits
* one using the method `parse` of each structs 
Is there a reason why theses two implementations cohabit? Using only one could reduce bugs and improve maintainability.
=> Fix some offsets computation when using scroll

src/pe/tls.rs
In favor to #458, I parted the change specifics to the possible TLS parser panic to this PR.
`TlsData::raw_data` can be `None` so instead of raising a malformed error if the address does not exists or does not lies in the binary, I made it simply `None`.
=> PE: fix TLS raw data parser

src/error.rs
Currently, only the `std::error::Error` trait is implemented for custom goblin error. Therefore the crate cannot be used with e.g. thiserror in `no-std` environments. Causing this error:
```
error[E0599]: the method `as_dyn_error` exists for reference `&goblin::error::Error`, but its trait bounds were not satisfied
--> uefi-loader/src/error.rs:42:12
|
42 |     Goblin(#[from] goblin::error::Error),
|            ^^^^^^^ method cannot be called on `&goblin::error::Error` due to unsatisfied trait bounds
|
::: /home/hannah/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/goblin-0.10.0/src/error.rs:14:1
|
14 | pub enum Error {
| -------------- doesn't satisfy `goblin::error::Error: AsDynError<'_>` or `goblin::error::Error: core::error::Error`
|
= note: the following trait bounds were not …
```
=> feat: add no-std error support

src/pe/mod.rs, src/pe/options.rs
Reason:
- sometimes I want to skip tls data parsing
Changes: 
- added `ParseOptions.parse_tls_data`
=> pe.options: added parse_tls_data option

src/pe/load_config.rs
- Resolves #481 
- Fixed invalid use of `.pread_with::<&[u8]>`
- ~~`PE::load_config_data` is now `None` if failing to parse.~~
=> PE: fix load config parser out of bounds

src/pe/exception.rs
Added parser for `C_SCOPE_TABLE` in `UnwindHandler::ExceptionHandler`.
This patch is backward compatible.
Reference:
- https://blog.talosintelligence.com/exceptional-behavior-windows-81-x64-seh/
> If the filter returns the code EXCEPTION_EXECUTE_HANDLER, the C specific handler prepares all the data needed to execute the relative exception handler and finally calls the routine [RtlUnwindEx](http://msdn.microsoft.com/en-us/library/windows/desktop/ms680615%28v=vs.85%29.aspx).
=> PE: Add parser for `C_SCOPE_TABLE`

src/pe/clr.rs, src/pe/mod.rs
- Addresses issue #315
Added CLR parser implementations as proposed in the issue.
- ~~Added CLR tables parser.~~
- Requires full re-implementation of [`IMetaDataTables`](https://learn.microsoft.com/windows/win32/api/rometadataapi/nn-rometadataapi-imetadatatables) where originally written in hard C++
- ~~Added CLR imports parser.~~
- Requires full re-implementation of [`IMetaDataImport`](https://learn.microsoft.com/windows/win32/api/rometadataapi/nn-rometadataapi-imetadataimport) where originally written in hard C++
=> PE: Add parser for .NET CLR

src/pe/section_table.rs
Original lifetime specification was wrong and made the compiler think the returned lifetime had to live as long as the section data, which it did not.
Before the fix, the following code did not compile:
```rs
// ... open PE file
let mut result = Vec::new();
for section in pe.sections {
result.push(section.data(file_bytes)); // compiler complains that section needs to live as long as result.
}
return result;
```
After the fix getting section data can outlive the section.
=> Fixed getting section data tainted section lifetime

src/pe/exception.rs
Implemented to-do of `UWOP_EPILOG` in unwind info v2 along with its tests.
Reference:
- https://github.com/BlancLoup/weekly-geekly.github.io/blob/1cbdf1c6127fcdaeda1f01bcbb006febd17d5a95/articles/322956/index.html
- https://github.com/Montura/cpp/blob/4393c678ee8e44dd98feb7a198c3983a6108cef8/src/exception_handling/msvc/eh_msvc_cxx_EH_x64.md?plain=1#L119
=> PE: Implement `UWOP_EPILOG` parsing for unwind info v2
