m4b/goblin

src/elf/_32/sym.rs
src/elf/_64/gnu_hash.rs
src/elf/_64/sym.rs
src/elf/mod.rs
src/elf/strtab.rs
src/mach/fat.rs
src/mach/mod.rs

Just a few readability nits – should be easy to review.

fixed some clippy warnings

---

Cargo.toml
src/elf/dyn.rs
src/elf/program_header.rs
src/elf/reloc.rs
src/elf/section_header.rs
src/elf/sym.rs

I'm not happy that some unsafe blocks returned, but the API wasn't entirely safe to begin with, so I figure this is better than just sitting on my frustration with the memory model.
Though it would be even better to implement _proper_ reading from files, endianness and all.

Update plain to latest version.

---

src/strtab.rs

Check overflow in strtab

---

src/elf/mod.rs

Check sh_link is in bounds

---

src/archive/mod.rs
src/strtab.rs
tests/archive.rs

This works on a Mac. I didn't personally test it on Linux, but Travis says it works there too. Closes #26.

Implement BSD-style `ar` support

---

src/elf/header.rs
src/elf/program_header.rs
src/elf/section_header.rs
src/elf/sym.rs
src/mach/load_command.rs
src/pe/import.rs
src/strtab.rs

These are just some minor adjustments that don't change the logic of the library.
Mostly guided by clippy.

Minor codestyle fixes

---

src/elf/mod.rs
src/elf/sym.rs

I want this to avoid potentially large and unneeded allocations for the symbol table. So with this, parsing the ELF header doesn't also parse all the symbols, which is useful if you don't care about the symbols. And the iterator lets me parse the symbols and put them in my own container, instead of requiring them all to be put in a Vec first.
This is all wrapped in `if_std!` because it needs `Sym`, so it's probably not what you want for #21. Let me know if you have ideas on how to adapt it for that.

elf: add Symtab and SymIterator

---

src/pe/section_table.rs

Based on https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx

Add flags for PE section characteristics

---

src/elf/reloc.rs

impl Debug for RelocIterator

---

src/elf/reloc.rs

Impl Debug for Rel

---

src/elf/compression_header.rs
src/elf/dyn.rs
src/elf/header.rs
src/elf/program_header.rs
src/elf/section_header.rs
src/elf/sym.rs
src/mach/fat.rs
src/mach/header.rs
src/strtab.rs

With #128 and #129, it should be sufficient to fix #24 .

Beautify debugging by using debug_struct

---

src/mach/exports.rs
src/mach/imports.rs
src/mach/symbols.rs

Hopefully this one is enough to to fix #24 .

Beautify debugging by using debug_struct for mach

---

src/elf/gnu_hash.rs
src/elf/mod.rs
src/lib.rs

Cleanup implementation of elf::gnu_hash::hash

---

src/pe/section_table.rs

pe: fix set_name_offset compilation for 32-bit

---

.travis.yml

I forgot to delete this in #196.

Fix nightly CI

---

src/elf/sym.rs

Also derive Copy trait because sym{32,64}::Sym have it
See the non-whitespace diff: https://github.com/m4b/goblin/pull/198/files?utf8=%E2%9C%93&diff=unified&w=1

split elf::Sym definition out of alloc gate

---

src/elf/gnu_hash.rs
src/elf/note.rs
src/elf/program_header.rs
src/elf/section_header.rs
src/elf/sym.rs
src/strtab.rs

Fix build and clippy warnings
Would be nice to enforce this in CI :-)

Fix build and clippy warnings

---

src/elf/header.rs

https://github.com/bminor/glibc/blob/bada2e312a8b94c5fc2f5571b249c71cb466a640/elf/elf.h#L135-L150

Complete ELFOSABI constants

---

src/strtab.rs

https://github.com/m4b/goblin/issues/300
In this PR we will work on documentation

Documented Note

---

src/pe/utils.rs

File_alignment check.

---

src/elf/reloc.rs

Minor documentation fix with missing column separator.

Fix documentation row

---

src/pe/debug.rs

Adds support for Codeview PDB 2.0 debug directory format.

Add support for Codeview PDB 2.0 debug directory format

---

src/pe/debug.rs

Found another integer overflow and possible out of bound memory access while fuzzing
[crash-ee0e9763c779daefdaae371ebe356938b39c9f9a.zip](https://github.com/user-attachments/files/19398690/crash-ee0e9763c779daefdaae371ebe356938b39c9f9a.zip)

pe.debug.POGOInfo.parse_with_opts - integer overflow + out of bound 

---

src/pe/load_config.rs
src/pe/mod.rs

Added parser for load config directory in PE32/64.
Ref:
- https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-image_load_config_directory64

PE: Add load config parser

---

src/pe/exception.rs

I had an issue where below assertion being triggered parsing `rustc.exe`. The unwind info stands correct.
```bash
cargo run --example rdr -- "path/to/rustc.exe"
```
As commented in the code in the patch, developers sometimes forget to align handy-written unwind infos (which becomes an edge case because is really a compiler's job to generate such), but the unwind info is correct anyway and we should not have that assertion.
https://github.com/m4b/goblin/blob/8e606d8a5aa2158f64ef82f6e279c6b182cc7b3f/src/pe/exception.rs#L576
---
Edit: temporaly fix is to use `[profile.dev] debug-assertions = false` in `Cargo.toml`

PE: Remove unwind info alignment assertion
